# Generated by Django 6.0.6 on 2026-06-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
