# Generated by Django 6.0.6 on 2026-06-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderapp', '0002_reminder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='priority',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
